"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { copyText } from "@/components/living/parts";
import { play, soundOn, setSound } from "@/lib/v6/sound";
import { record, type TrailEntry } from "@/lib/v6/trail";
import { findUrls } from "@/lib/pearl/resolve";
import { gameSegments, playGame } from "@/lib/games/ttt";
import { TRUSTED_ORIGINS } from "@/config/origin";

/** A small toast; role=status so it is announced. */
export function useToast() {
  const [msg, setMsg] = useState<string | null>(null);
  const t = useRef<ReturnType<typeof setTimeout> | null>(null);
  const say = (m: string) => { setMsg(m); if (t.current) clearTimeout(t.current); t.current = setTimeout(() => setMsg(null), 3200); };
  const node = msg ? <p role="status" className="toast glass-strong px-5 py-3 text-[0.92rem]">{msg}</p> : null;
  return { say, node };
}

/** Copy link + Copy for AI. The AI program is generated by the caller from the object itself. */
export function CopyPair({ url, program, title, primary = "ai", compact = false }: { url: string; program: string; title: string; primary?: "ai" | "link"; compact?: boolean }) {
  const { say, node } = useToast();
  const ai = async () => { const ok = await copyText(program); play("copy"); say(ok ? "Copied for your AI. Paste it into any AI, then bring back what it gives you." : "Couldn't copy. Select the text instead."); if (ok) record({ kind: "gave", url, title }); };
  const link = async () => { const ok = await copyText(url); play("copy"); say(ok ? "Link copied. The link is the thing." : "Couldn't copy."); };
  const cls = compact ? "!min-h-10 !px-4 !py-1.5 text-[0.88rem]" : "";
  return (
    <>
      <button type="button" onClick={ai} className={`${primary === "ai" ? "btn-glow" : "btn-glass"} ${cls}`}>Copy for AI</button>
      <button type="button" onClick={link} className={`${primary === "link" ? "btn-glow" : "btn-glass"} ${cls}`}>Copy link</button>
      {node}
    </>
  );
}

const TRUSTED = new Set(TRUSTED_ORIGINS.map((o) => new URL(o).host));
/** The first link in a pasted reply that belongs to this world. */
export function recognise(text: string): { path: string; kind: "game" | "pearl" | "world"; who: string | null } | null {
  for (const raw of findUrls(text)) {
    let u: URL; try { u = new URL(raw); } catch { continue; }
    if (!TRUSTED.has(u.host)) continue;
    const segs = gameSegments(raw);
    if (segs) { try { const g = playGame(segs); return { path: g.address, kind: "game", who: g.moves.at(-1)?.who ?? null }; } catch { continue; } }
    if (/^\/(e|p)(\/|$)/.test(u.pathname)) return { path: u.pathname + u.search, kind: "pearl", who: u.searchParams.get("by") };
    if (/^\/(live|x)\/map\//.test(u.pathname)) return { path: u.pathname.replace(/^\/x/, "/live"), kind: "world", who: null };
  }
  return null;
}

/** BRING IT BACK: paste what the AI replied; we find the thing it made and open it. Nothing is fetched. */
export function BringBack({ from, label = "Bring it back", hint = "Paste your AI's whole reply. We'll find the link it made." }: { from?: { url: string; title: string }; label?: string; hint?: string }) {
  const router = useRouter();
  const [v, setV] = useState("");
  const [err, setErr] = useState<string | null>(null);
  const go = () => {
    const r = recognise(v);
    if (!r) { setErr("No link from this world in that reply. If your AI couldn't open links, ask it to try again, or paste the link on its own."); play("unsure"); return; }
    play("return");
    record({ kind: "returned", url: r.path, title: r.kind === "game" ? "a game, brought back" : r.kind === "world" ? "a tiny world, brought back" : "a Pearl, brought back", parent: from?.url ?? null, who: r.who });
    router.push(r.path);
  };
  return (
    <form onSubmit={(e) => { e.preventDefault(); go(); }} className="space-y-2">
      <label htmlFor="bring-back" className="block font-serif text-xl">{label}</label>
      <p className="text-[0.88rem] text-ink-3">{hint}</p>
      <textarea id="bring-back" rows={3} value={v} onChange={(e) => { setV(e.target.value); setErr(null); }} className="w-full rounded-2xl border border-white/15 bg-white/5 p-3 font-mono text-[0.8rem] text-ink outline-none focus:border-emerald" placeholder="Here's my move: https://aanebed.vercel.app/g/ttt/4~you/0~claude" spellCheck={false} />
      <div className="flex flex-wrap items-center gap-3"><button type="submit" className="btn-glow !min-h-10 !py-1.5" disabled={!v.trim()}>Open what it made</button>{err && <span role="alert" className="text-[0.85rem] text-refuse">{err}</span>}</div>
    </form>
  );
}

/** Record that this object was opened (once per visit). */
export function Opened(e: Omit<TrailEntry, "at">) {
  useEffect(() => { record(e); play("open"); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [e.url]);
  return null;
}

export function SoundToggle() {
  const [on, setOn] = useState(false);
  useEffect(() => setOn(soundOn()), []);
  return (
    <button type="button" aria-pressed={on} onClick={() => { setSound(!on); setOn(!on); }} className="rounded-full px-2.5 py-1.5 text-[0.82rem] text-ink-2 hover:text-ink" title="Computational sound (optional)">
      {on ? "♪ sound on" : "♪ sound off"}
    </button>
  );
}
